fail_fast: true

repos:
  - repo: https://github.com/nozaq/pre-commit-deno
    rev: v0.1.0
    hooks:
      - id: deno-fmt
        files: \.(ts|tsx|js|jsx|json|jsonc)$
      - id: deno-lint
        files: \.(ts|tsx|js|jsx)$
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.4.0
    hooks:
      - id: stylelint
        args: [--fix]
        files: \.(css|scss|sass|less|html|js|jsx|ts|tsx)$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: [--fix, --config, .markdownlint.jsonc]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-executables-have-shebangs
        files: \.(sh)$
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        files: \.(sh)$
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        files: \.(sh|rs|js|ts|css|html)$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        files: \.(sh|rs|js|ts|css|html)$
      - id: check-toml
        files: \.toml$
      - id: check-yaml
        args: [--unsafe]
        files: \.(yaml|yml)$
      - id: pretty-format-json
        args: ['--autofix', '--indent=2', '--no-sort-keys']
        files: \.(json|jsonc)$
        exclude: |
            (?x)^(
                .devcontainer/devcontainer.json|
                .vscode/launch.json|
                .vscode/settings.json|
                .vscode/extensions.json|
            )$
